# Generated by Django 5.2 on 2025-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_questions',
            field=models.IntegerField(default=5),
        ),
    ]
